INSERT INTO FPL_STATS.FPL_SCHEMA.SOURCE_TEAMS (
    team_id,
    code,
    draw,
    form,
    loss,
    name,
    played,
    points,
    position,
    short_name,
    strength,
    team_division,
    unavailable,
    win,
    strength_overall_home,
    strength_overall_away,
    strength_attack_home,
    strength_attack_away,
    strength_defence_home,
    strength_defence_away,
    pulse_id,
    extraction_timestamp,
    extraction_date
)
SELECT 
    team.value:id::INTEGER as team_id,
    team.value:code::INTEGER as code,
    team.value:draw::INTEGER as draw,
    team.value:form::STRING as form,
    team.value:loss::INTEGER as loss,
    team.value:name::STRING as name,
    team.value:played::INTEGER as played,
    team.value:points::INTEGER as points,
    team.value:position::INTEGER as position,
    team.value:short_name::STRING as short_name,
    team.value:strength::INTEGER as strength,
    team.value:team_division::INTEGER as team_division,
    team.value:unavailable::BOOLEAN as unavailable,
    team.value:win::INTEGER as win,
    team.value:strength_overall_home::INTEGER as strength_overall_home,
    team.value:strength_overall_away::INTEGER as strength_overall_away,
    team.value:strength_attack_home::INTEGER as strength_attack_home,
    team.value:strength_attack_away::INTEGER as strength_attack_away,
    team.value:strength_defence_home::INTEGER as strength_defence_home,
    team.value:strength_defence_away::INTEGER as strength_defence_away,
    team.value:pulse_id::INTEGER as pulse_id,
    extraction_timestamp,
    extraction_date
FROM FPL_STATS.FPL_SCHEMA.STAGING_BOOTSTRAP,
LATERAL FLATTEN(input => raw_data:teams) as team;