version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: fantasy-football-db
    environment:
      POSTGRES_DB: fantasy_football
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: fantasy-football-backend
    environment:
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/fantasy_football
      JWT_SECRET: your-jwt-secret-key
      NODE_ENV: development
      PORT: 3001
      SNOWFLAKE_ACCOUNT: IVGPXQI-YE27103
      SNOWFLAKE_USER: FPL_ETL_DEV_READ_USER
      SNOWFLAKE_PASSWORD: gnp1guf7ptx2ZPK!wra
      SNOWFLAKE_WAREHOUSE: FPL_ETL_DEV_WAREHOUSE
      SNOWFLAKE_DATABASE: FPL_STATS
      SNOWFLAKE_SCHEMA: FPL_SCHEMA
      SNOWFLAKE_ROLE: SNOWFLAKE_READ_ROLE
    ports:
      - "3001:3001"
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./backend:/app
      - /app/node_modules
    command: sh -c "npx prisma migrate deploy && npm run dev"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: fantasy-football-frontend
    environment:
      VITE_API_URL: http://localhost:3000
    ports:
      - "3000:3000"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: npm run dev

volumes:
  postgres_data: