CREATE TABLE IF NOT EXISTS FPL_STATS.FPL_SCHEMA.SOURCE_EVENTS (
    event_id INTEGER PRIMARY KEY,
    name STRING,
    deadline_time TIMESTAMP_NTZ,
    deadline_time_epoch INTEGER,
    release_time TIMESTAMP_NTZ,
    average_entry_score INTEGER,
    finished BOOLEAN,
    data_checked BOOLEAN,
    highest_scoring_entry INTEGER,
    is_previous BOOLEAN,
    is_current BOOLEAN,
    is_next BOOLEAN,
    cup_leagues_created BOOLEAN,
    h2h_ko_matches_created BOOLEAN,
    can_enter BOOLEAN,
    can_manage BOOLEAN,
    chip_plays VARIANT,
    most_selected INTEGER,
    most_transferred_in INTEGER,
    top_element INTEGER,
    top_element_info VARIANT,
    transfers_made INTEGER,
    most_captained INTEGER,
    most_vice_captained INTEGER,
    ranked_count INTEGER,
    extraction_timestamp TIMESTAMP_NTZ,
    extraction_date DATE
);