INSERT INTO FPL_STATS.FPL_SCHEMA.SOURCE_EVENTS (
    event_id,
    name,
    deadline_time,
    deadline_time_epoch,
    release_time,
    average_entry_score,
    finished,
    data_checked,
    highest_scoring_entry,
    is_previous,
    is_current,
    is_next,
    cup_leagues_created,
    h2h_ko_matches_created,
    can_enter,
    can_manage,
    chip_plays,
    most_selected,
    most_transferred_in,
    top_element,
    top_element_info,
    transfers_made,
    most_captained,
    most_vice_captained,
    ranked_count,
    extraction_timestamp,
    extraction_date
)
SELECT 
    event.value:id::INTEGER as event_id,
    event.value:name::STRING as name,
    event.value:deadline_time::TIMESTAMP_NTZ as deadline_time,
    event.value:deadline_time_epoch::INTEGER as deadline_time_epoch,
    event.value:release_time::TIMESTAMP_NTZ as release_time,
    event.value:average_entry_score::INTEGER as average_entry_score,
    event.value:finished::BOOLEAN as finished,
    event.value:data_checked::BOOLEAN as data_checked,
    event.value:highest_scoring_entry::INTEGER as highest_scoring_entry,
    event.value:is_previous::BOOLEAN as is_previous,
    event.value:is_current::BOOLEAN as is_current,
    event.value:is_next::BOOLEAN as is_next,
    event.value:cup_leagues_created::BOOLEAN as cup_leagues_created,
    event.value:h2h_ko_matches_created::BOOLEAN as h2h_ko_matches_created,
    event.value:can_enter::BOOLEAN as can_enter,
    event.value:can_manage::BOOLEAN as can_manage,
    event.value:chip_plays as chip_plays,
    event.value:most_selected::INTEGER as most_selected,
    event.value:most_transferred_in::INTEGER as most_transferred_in,
    event.value:top_element::INTEGER as top_element,
    event.value:top_element_info as top_element_info,
    event.value:transfers_made::INTEGER as transfers_made,
    event.value:most_captained::INTEGER as most_captained,
    event.value:most_vice_captained::INTEGER as most_vice_captained,
    event.value:ranked_count::INTEGER as ranked_count,
    extraction_timestamp,
    extraction_date
FROM FPL_STATS.FPL_SCHEMA.STAGING_BOOTSTRAP,
LATERAL FLATTEN(input => raw_data:events) as event;