INSERT INTO FPL_STATS.FPL_SCHEMA.SOURCE_PLAYERS (
    player_id,
    chance_of_playing_next_round,
    chance_of_playing_this_round,
    code,
    cost_change_event,
    cost_change_event_fall,
    cost_change_start,
    cost_change_start_fall,
    dreamteam_count,
    element_type,
    ep_next,
    ep_this,
    event_points,
    first_name,
    form,
    id,
    in_dreamteam,
    news,
    news_added,
    now_cost,
    photo,
    points_per_game,
    second_name,
    selected_by_percent,
    special,
    squad_number,
    status,
    team,
    team_code,
    total_points,
    transfers_in,
    transfers_in_event,
    transfers_out,
    transfers_out_event,
    value_form,
    value_season,
    web_name,
    minutes,
    goals_scored,
    assists,
    clean_sheets,
    goals_conceded,
    own_goals,
    penalties_saved,
    penalties_missed,
    yellow_cards,
    red_cards,
    saves,
    bonus,
    bps,
    influence,
    creativity,
    threat,
    ict_index,
    starts,
    expected_goals,
    expected_assists,
    expected_goal_involvements,
    expected_goals_conceded,
    influence_rank,
    influence_rank_type,
    creativity_rank,
    creativity_rank_type,
    threat_rank,
    threat_rank_type,
    ict_index_rank,
    ict_index_rank_type,
    corners_and_indirect_freekicks_order,
    corners_and_indirect_freekicks_text,
    direct_freekicks_order,
    direct_freekicks_text,
    penalties_order,
    penalties_text,
    expected_goals_per_90,
    saves_per_90,
    expected_assists_per_90,
    expected_goal_involvements_per_90,
    expected_goals_conceded_per_90,
    goals_conceded_per_90,
    now_cost_rank,
    now_cost_rank_type,
    form_rank,
    form_rank_type,
    points_per_game_rank,
    points_per_game_rank_type,
    selected_rank,
    selected_rank_type,
    starts_per_90,
    clean_sheets_per_90,
    extraction_timestamp,
    extraction_date
)
SELECT 
    player.value:id::INTEGER as player_id,
    player.value:chance_of_playing_next_round::INTEGER as chance_of_playing_next_round,
    player.value:chance_of_playing_this_round::INTEGER as chance_of_playing_this_round,
    player.value:code::INTEGER as code,
    player.value:cost_change_event::INTEGER as cost_change_event,
    player.value:cost_change_event_fall::INTEGER as cost_change_event_fall,
    player.value:cost_change_start::INTEGER as cost_change_start,
    player.value:cost_change_start_fall::INTEGER as cost_change_start_fall,
    player.value:dreamteam_count::INTEGER as dreamteam_count,
    player.value:element_type::INTEGER as element_type,
    player.value:ep_next::FLOAT as ep_next,
    player.value:ep_this::FLOAT as ep_this,
    player.value:event_points::INTEGER as event_points,
    player.value:first_name::STRING as first_name,
    player.value:form::FLOAT as form,
    player.value:id::INTEGER as id,
    player.value:in_dreamteam::BOOLEAN as in_dreamteam,
    player.value:news::STRING as news,
    player.value:news_added::TIMESTAMP_NTZ as news_added,
    player.value:now_cost::INTEGER as now_cost,
    player.value:photo::STRING as photo,
    player.value:points_per_game::FLOAT as points_per_game,
    player.value:second_name::STRING as second_name,
    player.value:selected_by_percent::FLOAT as selected_by_percent,
    player.value:special::BOOLEAN as special,
    player.value:squad_number::INTEGER as squad_number,
    player.value:status::STRING as status,
    player.value:team::INTEGER as team,
    player.value:team_code::INTEGER as team_code,
    player.value:total_points::INTEGER as total_points,
    player.value:transfers_in::INTEGER as transfers_in,
    player.value:transfers_in_event::INTEGER as transfers_in_event,
    player.value:transfers_out::INTEGER as transfers_out,
    player.value:transfers_out_event::INTEGER as transfers_out_event,
    player.value:value_form::FLOAT as value_form,
    player.value:value_season::FLOAT as value_season,
    player.value:web_name::STRING as web_name,
    player.value:minutes::INTEGER as minutes,
    player.value:goals_scored::INTEGER as goals_scored,
    player.value:assists::INTEGER as assists,
    player.value:clean_sheets::INTEGER as clean_sheets,
    player.value:goals_conceded::INTEGER as goals_conceded,
    player.value:own_goals::INTEGER as own_goals,
    player.value:penalties_saved::INTEGER as penalties_saved,
    player.value:penalties_missed::INTEGER as penalties_missed,
    player.value:yellow_cards::INTEGER as yellow_cards,
    player.value:red_cards::INTEGER as red_cards,
    player.value:saves::INTEGER as saves,
    player.value:bonus::INTEGER as bonus,
    player.value:bps::INTEGER as bps,
    player.value:influence::FLOAT as influence,
    player.value:creativity::FLOAT as creativity,
    player.value:threat::FLOAT as threat,
    player.value:ict_index::FLOAT as ict_index,
    player.value:starts::INTEGER as starts,
    player.value:expected_goals::FLOAT as expected_goals,
    player.value:expected_assists::FLOAT as expected_assists,
    player.value:expected_goal_involvements::FLOAT as expected_goal_involvements,
    player.value:expected_goals_conceded::FLOAT as expected_goals_conceded,
    player.value:influence_rank::INTEGER as influence_rank,
    player.value:influence_rank_type::INTEGER as influence_rank_type,
    player.value:creativity_rank::INTEGER as creativity_rank,
    player.value:creativity_rank_type::INTEGER as creativity_rank_type,
    player.value:threat_rank::INTEGER as threat_rank,
    player.value:threat_rank_type::INTEGER as threat_rank_type,
    player.value:ict_index_rank::INTEGER as ict_index_rank,
    player.value:ict_index_rank_type::INTEGER as ict_index_rank_type,
    player.value:corners_and_indirect_freekicks_order::INTEGER as corners_and_indirect_freekicks_order,
    player.value:corners_and_indirect_freekicks_text::STRING as corners_and_indirect_freekicks_text,
    player.value:direct_freekicks_order::INTEGER as direct_freekicks_order,
    player.value:direct_freekicks_text::STRING as direct_freekicks_text,
    player.value:penalties_order::INTEGER as penalties_order,
    player.value:penalties_text::STRING as penalties_text,
    player.value:expected_goals_per_90::FLOAT as expected_goals_per_90,
    player.value:saves_per_90::FLOAT as saves_per_90,
    player.value:expected_assists_per_90::FLOAT as expected_assists_per_90,
    player.value:expected_goal_involvements_per_90::FLOAT as expected_goal_involvements_per_90,
    player.value:expected_goals_conceded_per_90::FLOAT as expected_goals_conceded_per_90,
    player.value:goals_conceded_per_90::FLOAT as goals_conceded_per_90,
    player.value:now_cost_rank::INTEGER as now_cost_rank,
    player.value:now_cost_rank_type::INTEGER as now_cost_rank_type,
    player.value:form_rank::INTEGER as form_rank,
    player.value:form_rank_type::INTEGER as form_rank_type,
    player.value:points_per_game_rank::INTEGER as points_per_game_rank,
    player.value:points_per_game_rank_type::INTEGER as points_per_game_rank_type,
    player.value:selected_rank::INTEGER as selected_rank,
    player.value:selected_rank_type::INTEGER as selected_rank_type,
    player.value:starts_per_90::FLOAT as starts_per_90,
    player.value:clean_sheets_per_90::FLOAT as clean_sheets_per_90,
    extraction_timestamp,
    extraction_date
FROM FPL_STATS.FPL_SCHEMA.STAGING_BOOTSTRAP,
LATERAL FLATTEN(input => raw_data:elements) as player;