CREATE OR REPLACE TABLE FPL_STATS.FPL_SCHEMA.DIM_STANDINGS (
    team_id INTEGER PRIMARY KEY,
    code INTEGER,
    draw INTEGER,
    form STRING,
    loss INTEGER,
    name STRING,
    played INTEGER,
    points INTEGER,
    position INTEGER,
    short_name STRING,
    strength INTEGER,
    team_division INTEGER,
    unavailable BOOLEAN,
    win INTEGER,
    strength_overall_home INTEGER,
    strength_overall_away INTEGER,
    strength_attack_home INTEGER,
    strength_attack_away INTEGER,
    strength_defence_home INTEGER,
    strength_defence_away INTEGER,
    pulse_id INTEGER,
    extraction_timestamp TIMESTAMP_NTZ,
    extraction_date DATE
);
