AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: FPL Stats ETL Pipeline - Daily and Weekly Lambda Functions

Parameters:
  S3BucketName:
    Type: String
    Description: S3 bucket name for data lake
    Default: fpl-datalake

Globals:
  Function:
    Runtime: python3.13
    Architectures:
      - x86_64
    Timeout: 900
    MemorySize: 512
    Environment:
      Variables:
        S3_BUCKET_NAME: !Ref S3BucketName
        AWS_REGION: !Ref AWS::Region
        LOG_LEVEL: INFO

Resources:
  FPLETLDailyFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: fpl-etl-daily
      CodeUri: .
      Description: FPL Daily ETL Pipeline (Extract, Source, Stage)
      Handler: main.lambda_handler
      Timeout: 900
      MemorySize: 1024
      EphemeralStorage:
        Size: 2048
      EventInvokeConfig:
        MaximumEventAgeInSeconds: 21600
        MaximumRetryAttempts: 2
      Events:
        DailySchedule:
          Type: Schedule
          Properties:
            Schedule: cron(0 2 * * ? *)
            Description: Run daily ETL at 2 AM UTC
            Input: |
              {
                "detail": {
                  "schedule": "daily",
                  "phase": "all"
                }
              }
      Policies:
        - S3CrudPolicy:
            BucketName: !Ref S3BucketName
        - Statement:
            - Effect: Allow
              Action:
                - logs:CreateLogGroup
                - logs:CreateLogStream
                - logs:PutLogEvents
              Resource: !Sub arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/lambda/fpl-etl-daily:*
            - Effect: Allow
              Action:
                - ssm:GetParameter
                - ssm:GetParameters
              Resource: !Sub arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/etl/*
      RecursiveLoop: Terminate
    Metadata:
      BuildMethod: python3.13
      BuildArchitecture: x86_64

  FPLETLWeeklyFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: fpl-etl-weekly
      CodeUri: .
      Description: FPL Weekly ETL Pipeline (Extract, Source, Stage)
      Handler: main.lambda_handler
      Timeout: 900
      MemorySize: 2048
      EphemeralStorage:
        Size: 4096
      EventInvokeConfig:
        MaximumEventAgeInSeconds: 21600
        MaximumRetryAttempts: 2
      Events:
        WeeklySchedule:
          Type: Schedule
          Properties:
            Schedule: cron(0 3 ? * SUN *)
            Description: Run weekly ETL at 3 AM UTC on Sundays
            Input: |
              {
                "detail": {
                  "schedule": "weekly",
                  "phase": "all"
                }
              }
      Policies:
        - S3CrudPolicy:
            BucketName: !Ref S3BucketName
        - Statement:
            - Effect: Allow
              Action:
                - logs:CreateLogGroup
                - logs:CreateLogStream
                - logs:PutLogEvents
              Resource: !Sub arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/lambda/fpl-etl-weekly:*
            - Effect: Allow
              Action:
                - ssm:GetParameter
                - ssm:GetParameters
              Resource: !Sub arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/etl/*
      RecursiveLoop: Terminate
    Metadata:
      BuildMethod: python3.13
      BuildArchitecture: x86_64

Outputs:
  FPLETLDailyFunctionArn:
    Description: ARN of the Daily ETL Lambda Function
    Value: !GetAtt FPLETLDailyFunction.Arn
    Export:
      Name: FPLETLDailyFunctionArn

  FPLETLWeeklyFunctionArn:
    Description: ARN of the Weekly ETL Lambda Function
    Value: !GetAtt FPLETLWeeklyFunction.Arn
    Export:
      Name: FPLETLWeeklyFunctionArn

  S3BucketName:
    Description: S3 Bucket for FPL Data Lake
    Value: !Ref S3BucketName
