CREATE TABLE IF NOT EXISTS SOURCE_PLAYER_HISTORY_PAST (
    season_name STRING,
    element_code INTEGER,
    start_cost INTEGER,
    end_cost INTEGER,
    total_points INTEGER,
    minutes INTEGER,
    goals_scored INTEGER,
    assists INTEGER,
    clean_sheets INTEGER,
    goals_conceded INTEGER,
    own_goals INTEGER,
    penalties_saved INTEGER,
    penalties_missed INTEGER,
    yellow_cards INTEGER,
    red_cards INTEGER,
    saves INTEGER,
    bonus INTEGER,
    bps INTEGER,
    influence FLOAT,
    creativity FLOAT,
    threat FLOAT,
    ict_index FLOAT,
    starts INTEGER,
    expected_goals FLOAT,
    expected_assists FLOAT,
    expected_goal_involvements FLOAT,
    expected_goals_conceded FLOAT,
    player_id INTEGER,
    extraction_timestamp TIMESTAMP_NTZ,
    extraction_date DATE,
    PRIMARY KEY (season_name, element_code, player_id)
);