INSERT INTO SOURCE_PLAYER_HISTORY_PAST (
    season_name,
    element_code,
    start_cost,
    end_cost,
    total_points,
    minutes,
    goals_scored,
    assists,
    clean_sheets,
    goals_conceded,
    own_goals,
    penalties_saved,
    penalties_missed,
    yellow_cards,
    red_cards,
    saves,
    bonus,
    bps,
    influence,
    creativity,
    threat,
    ict_index,
    starts,
    expected_goals,
    expected_assists,
    expected_goal_involvements,
    expected_goals_conceded,
    player_id,
    extraction_timestamp,
    extraction_date
)
SELECT 
    history.value:season_name::STRING as season_name,
    history.value:element_code::INTEGER as element_code,
    history.value:start_cost::INTEGER as start_cost,
    history.value:end_cost::INTEGER as end_cost,
    history.value:total_points::INTEGER as total_points,
    history.value:minutes::INTEGER as minutes,
    history.value:goals_scored::INTEGER as goals_scored,
    history.value:assists::INTEGER as assists,
    history.value:clean_sheets::INTEGER as clean_sheets,
    history.value:goals_conceded::INTEGER as goals_conceded,
    history.value:own_goals::INTEGER as own_goals,
    history.value:penalties_saved::INTEGER as penalties_saved,
    history.value:penalties_missed::INTEGER as penalties_missed,
    history.value:yellow_cards::INTEGER as yellow_cards,
    history.value:red_cards::INTEGER as red_cards,
    history.value:saves::INTEGER as saves,
    history.value:bonus::INTEGER as bonus,
    history.value:bps::INTEGER as bps,
    history.value:influence::FLOAT as influence,
    history.value:creativity::FLOAT as creativity,
    history.value:threat::FLOAT as threat,
    history.value:ict_index::FLOAT as ict_index,
    history.value:starts::INTEGER as starts,
    history.value:expected_goals::FLOAT as expected_goals,
    history.value:expected_assists::FLOAT as expected_assists,
    history.value:expected_goal_involvements::FLOAT as expected_goal_involvements,
    history.value:expected_goals_conceded::FLOAT as expected_goals_conceded,
    player_data.key::INTEGER as player_id,
    extraction_timestamp,
    extraction_date
FROM STAGING_PLAYER_DETAILS,
LATERAL FLATTEN(input => raw_data) as player_data,
LATERAL FLATTEN(input => player_data.value:history_past) as history;