INSERT INTO FPL_STATS.FPL_SCHEMA.SOURCE_PLAYER_HISTORY (
    element,
    fixture,
    opponent_team,
    total_points,
    was_home,
    kickoff_time,
    team_h_score,
    team_a_score,
    round,
    minutes,
    goals_scored,
    assists,
    clean_sheets,
    goals_conceded,
    own_goals,
    penalties_saved,
    penalties_missed,
    yellow_cards,
    red_cards,
    saves,
    bonus,
    bps,
    influence,
    creativity,
    threat,
    ict_index,
    starts,
    expected_goals,
    expected_assists,
    expected_goal_involvements,
    expected_goals_conceded,
    value,
    transfers_balance,
    selected,
    transfers_in,
    transfers_out,
    player_id,
    extraction_timestamp,
    extraction_date
)
SELECT 
    history.value:element::INTEGER as element,
    history.value:fixture::INTEGER as fixture,
    history.value:opponent_team::INTEGER as opponent_team,
    history.value:total_points::INTEGER as total_points,
    history.value:was_home::BOOLEAN as was_home,
    history.value:kickoff_time::TIMESTAMP_NTZ as kickoff_time,
    history.value:team_h_score::INTEGER as team_h_score,
    history.value:team_a_score::INTEGER as team_a_score,
    history.value:round::INTEGER as round,
    history.value:minutes::INTEGER as minutes,
    history.value:goals_scored::INTEGER as goals_scored,
    history.value:assists::INTEGER as assists,
    history.value:clean_sheets::INTEGER as clean_sheets,
    history.value:goals_conceded::INTEGER as goals_conceded,
    history.value:own_goals::INTEGER as own_goals,
    history.value:penalties_saved::INTEGER as penalties_saved,
    history.value:penalties_missed::INTEGER as penalties_missed,
    history.value:yellow_cards::INTEGER as yellow_cards,
    history.value:red_cards::INTEGER as red_cards,
    history.value:saves::INTEGER as saves,
    history.value:bonus::INTEGER as bonus,
    history.value:bps::INTEGER as bps,
    history.value:influence::FLOAT as influence,
    history.value:creativity::FLOAT as creativity,
    history.value:threat::FLOAT as threat,
    history.value:ict_index::FLOAT as ict_index,
    history.value:starts::INTEGER as starts,
    history.value:expected_goals::FLOAT as expected_goals,
    history.value:expected_assists::FLOAT as expected_assists,
    history.value:expected_goal_involvements::FLOAT as expected_goal_involvements,
    history.value:expected_goals_conceded::FLOAT as expected_goals_conceded,
    history.value:value::INTEGER as value,
    history.value:transfers_balance::INTEGER as transfers_balance,
    history.value:selected::INTEGER as selected,
    history.value:transfers_in::INTEGER as transfers_in,
    history.value:transfers_out::INTEGER as transfers_out,
    player_data.key::INTEGER as player_id,
    extraction_timestamp,
    extraction_date
FROM FPL_STATS.FPL_SCHEMA.STAGING_PLAYER_DETAILS,
LATERAL FLATTEN(input => raw_data) as player_data,
LATERAL FLATTEN(input => player_data.value:history) as history;