INSERT INTO FPL_STATS.FPL_SCHEMA.SOURCE_PLAYER_FIXTURES (
    fixture_id,
    event,
    opponent_team,
    opponent_team_name,
    opponent_team_short_name,
    is_home,
    difficulty,
    kickoff_time,
    team_h,
    team_a,
    team_h_score,
    team_a_score,
    finished,
    minutes,
    provisional_start_time,
    finished_provisional,
    event_name,
    player_id,
    extraction_timestamp,
    extraction_date
)
SELECT 
    fixture.value:id::INTEGER as fixture_id,
    fixture.value:event::INTEGER as event,
    fixture.value:opponent_team::INTEGER as opponent_team,
    fixture.value:opponent_team_name::STRING as opponent_team_name,
    fixture.value:opponent_team_short_name::STRING as opponent_team_short_name,
    fixture.value:is_home::BOOLEAN as is_home,
    fixture.value:difficulty::INTEGER as difficulty,
    fixture.value:kickoff_time::TIMESTAMP_NTZ as kickoff_time,
    fixture.value:team_h::INTEGER as team_h,
    fixture.value:team_a::INTEGER as team_a,
    fixture.value:team_h_score::INTEGER as team_h_score,
    fixture.value:team_a_score::INTEGER as team_a_score,
    fixture.value:finished::BOOLEAN as finished,
    fixture.value:minutes::INTEGER as minutes,
    fixture.value:provisional_start_time::BOOLEAN as provisional_start_time,
    fixture.value:finished_provisional::BOOLEAN as finished_provisional,
    fixture.value:event_name::STRING as event_name,
    player_data.key::INTEGER as player_id,
    extraction_timestamp,
    extraction_date
FROM FPL_STATS.FPL_SCHEMA.STAGING_PLAYER_DETAILS,
LATERAL FLATTEN(input => raw_data) as player_data,
LATERAL FLATTEN(input => player_data.value:fixtures) as fixture;